[package]
name = "maxcom-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "MAXCOM 传输层（串口/TCP/UDP/SSH/Telnet）+ 会话线程编排"

[dependencies]
maxcom-core = { path = "../maxcom-core" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
crossbeam-channel = "0.5"
telnet = "0.2"
russh = { version = "0.63", default-features = false, features = ["ring", "rsa"] }
tokio = { version = "1", features = ["rt-multi-thread", "time"] }
bytes = "1"
probe-rs = { version = "0.32", default-features = false, features = ["builtin-targets", "builtin-formats", "cmsisdap_v1"], optional = true }

[features]
default = ["serial"]
serial = ["dep:serialport"]
rtt = ["dep:probe-rs"]

[dependencies.serialport]
version = "4"
optional = true
